apiVersion: v1
kind: Service
metadata:
  name: {{ include "xapp-demo.fullname" . }}
  labels:
    app: {{ include "xapp-demo.fullname" . }}
spec:
  type: NodePort
  ports:
    - name: grpc
      port: {{ .Values.service.grpc.port }}
  selector:
    name: {{ include "xapp-demo.fullname" . }}